
newlic = {
    '00': 'none',                     '01' : 'Nintendo',           '08' : 'Capcom',
    '13': 'electronic arts',          '18' : 'Hudson Soft',         '19' : 'b-ai',
    '20': 'kss',                      '22' : 'pow',                '24' : 'pcm complete',
    '25': 'san-x',                    '28' : 'Kemco japan',        '29' : 'seta',
    '30': 'viacom',                   '31' : 'nintendo',           '32' : 'bandia',
    '33': 'Ocean/acclaim',            '34' : 'Konami',             '35' : 'hector',
    '37': 'Taito',                    '38' : 'Hudson',             '39' : 'banpresto',
    '41': 'ubi soft',                 '42' : 'atlus',              '44' : 'malibu',
    '46': 'angel',                    '47' : 'bullet-proof',       '49' : 'irem',
    '50': 'Absolute',                 '51' : 'acclaim',            '52' : 'activision',
    '53': 'American Sammy',           '54' : 'Konami',             '55' : 'hi tech entertainment',
    '56': 'LJN',                      '57' : 'matchbox',           '58' : 'mattel',
    '59': 'milton bradley',           '60' : 'titus',              '61' : 'virgin',
    '64': 'lucasarts',                '67' : 'Ocean',              '69' : 'electronic arts',
    '70': 'infogrames',               '71' : 'Interplay',          '72' : 'broderbund',
    '73': 'sculptured',               '75' : 'SCI',                '78' : 't*hq',
    '79': 'accolade',                 '80' : 'misawa',             '83' : 'lozc',
    '86': 'tokuma shoten i*',         '87' : 'tsukuda ori*',       '91' : 'chun soft',
    '92': 'video system',             '93' : 'Ocean/acclaim',      '95' : 'varie',
    '96': 'yonezawa/s\'pal',           '97' : 'kaneko',             '99' : 'pack in soft',
    'B4' : 'Enix', 
    'A4': 'Konami',
    'C3': 'Squaresoft',
    '8H': 'TNN',
    'BJ': 'Compile',
    'EB': 'Atlus',
    'E9': 'Natsume',
}


oldlic = {
    0x01 : 'Nintendo',           0x08 : 'Capcom',
    0x09 : 'hot-b',              0x0A : 'Jaleco',             0x0B : 'coconuts',
    0x0C : 'elite systems',      0x13 : 'electronic arts',    0x18 : 'hudsonsoft',
    0x19 : 'itc entertainment',  0x1A : 'yanoman',            0x1D : 'clary',
    0x1F : 'virgin',             0x24 : 'pcm complete',       0x25 : 'san-x',
    0x28 : 'kotobuki systems',   0x29 : 'seta',               0x30 : 'infogrames',
    0x31 : 'nintendo',           0x32 : 'bandai',
    0x34 : 'Konami',             0x35 : 'hector',             0x38 : 'Capcom',
    0x39 : 'banpresto',          0x3C : '*entertainment i',   0x3E : 'gremlin',
    0x40 : 'Seika',
    0x41 : 'Ubisoft',            0x42 : 'Atlus',              0x44 : 'malibu',
    0x46 : 'angel',              0x47 : 'spectrum holoby',    0x49 : 'irem',
    0x4A : 'virgin',             0x4D : 'malibu',             0x4F : 'U.S. Gold',
    0x50 : 'Absolute',           0x51 : 'acclaim',            0x52 : 'activision',
    0x53 : 'American Sammy',     0x54 : 'gametek',            0x55 : 'park place',
    0x56 : 'ljn',                0x57 : 'matchbox',           0x59 : 'milton bradley',
    0x5A : 'mindscape',          0x5B : 'romstar',            0x5C : 'Naxat Soft',
    0x5D : 'Tradewest',          0x60 : 'titus',              0x61 : 'virgin',
    0x67 : 'Ocean',              0x69 : 'electronic arts',    0x6E : 'elite systems',
    0x6F : 'electro brain',      0x70 : 'infogrames',         0x71 : 'Interplay',
    0x72 : 'broderbund',         0x73 : 'sculptered soft',    0x75 : 'the sales curve',
    0x78 : 't*hq',               0x79 : 'accolade',           0x7A : 'triffix entertainment',
    0x7C : 'microprose',         0x7F : 'Kemco',              0x80 : 'misawa entertainment',
    0x83 : 'lozc',               0x86 : '*tokuma shoten i',   0x8B : 'Bullet-Proof Software',
    0x8C : 'vic tokai',          0x8E : 'ape',                0x8F : 'i\'max',
    0x91 : 'chun soft',          0x92 : 'video system',       0x93 : 'tsuburava',
    0x95 : 'varie',              0x96 : 'yonezawa/s\'pal',     0x97 : 'kaneko',
    0x99 : 'arc',                0x9A : 'nihon bussan',       0x9B : 'Tecmo',
    0x9C : 'imagineer',          0x9D : 'banpresto',          0x9F : 'nova',
    0xA1 : 'hori electric',      0xA2 : 'bandai',             0xA4 : 'Konami',
    0xA6 : 'kawada',             0xA7 : 'takara',             0xA9 : 'technos japan',
    0xAA : 'broderbund',         0xAC : 'toei animation',     0xAD : 'toho',
    0xAF : 'namco',              0xB0 : 'acclaim',            0xB1 : 'Ascii or Nexoft',
    0xB2 : 'bandai',             0xB4 : 'Enix',               0xB6 : 'Hal',
    0xB7 : 'SNK',                0xB9 : 'pony canyon',        0xBA : '*culture brain o',
    0xBB : 'Sunsoft',            0xBD : 'Sony Imagesoft',     0xBF : 'sammy',
    0xC0 : 'Taito',              0xC2 : 'Kemco',              0xC3 : 'Squaresoft',
    0xC4 : '*tokuma shoten i',   0xC5 : 'data east',          0xC6 : 'tonkin house',
    0xC8 : 'koei',               0xC9 : 'ufl',                0xCA : 'Ultra',
    0xCB : 'vap',                0xCC : 'use',                0xCD : 'meldac',
    0xCE : '*pony canyon or',    0xCF : 'angel',              0xD0 : 'Taito',
    0xD1 : 'sofel',              0xD2 : 'quest',              0xD3 : 'sigma enterprises',
    0xD4 : 'ask kodansha',       0xD6 : 'Naxat Soft',         0xD7 : 'copya systems',
    0xD9 : 'banpresto',          0xDA : 'tomy',               0xDB : 'ljn',
    0xDD : 'ncs',                0xDE : 'human',              0xDF : 'altron',
    0xE0 : 'Jaleco',             0xE1 : 'towachiki',          0xE2 : 'uutaka',
    0xE3 : 'varie',              0xE5 : 'epoch',              0xE7 : 'athena',
    0xE8 : 'asmik',              0xE9 : 'Natsume',            0xEA : 'king records',
    0xEB : 'atlus',              0xEC : 'epic/sony records',  0xEE : 'igs',
    0xF0 : 'a wave',             0xF3 : 'extreme entertainment',  0xFF : 'ljn'
    }
